
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhlpvajljyaopjquxbir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpobHB2YWpsanlhb3BqcXV4YmlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDA5NjAsImV4cCI6MjA1OTg3Njk2MH0.7NDMQ9ZDPswmfBdlRaB32B_3AHmq04fs6E0VL86OtSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
